#!/usr/bin/env bash
# This scripts configures a brand new Ubuntu machine to configure (Nginx)
# so that its HTTP response contains a custom header on (web 01 and web 02)
# the name of the custom HTTP must be ` X-Served-By` and the value of the
# custom HTTP header is the hostname of the server Nginx is running on

# update packages
apt-get update

# Install nginx
apt-get install -y nginx

# create directory if not exist
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Best school" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Page not avaialable" > /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root	/var/www/html
	index	index.html index.htm;

	location /redirect_me {
		return 301 http://cuberule.com/;
	}

	error_page 404 /404.html;
	location /404 {
	  root /var/www/html
	  internal;
  }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

