#!/usr/bin/env bash
# Add HAProxy PPA
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get update

# Install HAProxy
apt-get install -y haproxy

# Enable HAProxy
echo "ENABLED=1" >> /etc/default/haproxy

# Backup existing HAProxy configuration
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Create a new HAProxy configuration file
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000
    timeout client 10000
    timeout server 10000

frontend memaame_frontend
    bind 0.0.0.0:80
    mode http
    default_backend memaame_backend

backend memaame_backend
    balance roundrobin
    option httpclose
    option forwardfor
    server 310219-web-01 310219-54.87.242.205:80 check
    server 310219-web-02 310219-100.26.212.66:80 check
EOF

# Start HAProxy service
systemctl start haproxy

# Enable HAProxy to start on boot
systemctl enable haproxy

