#!/usr/bin/env bash
# Update package repository and install necessary tools
# Add HAProxy PPA repository
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5

# Update repository information again after adding PPA
apt-get update

# Install HAProxy
apt-get install -y haproxy

# Enable HAProxy service in default configuration file
echo "ENABLED=1" >> /etc/default/haproxy

# Backup the original HAProxy configuration file if it exists
if [ -f /etc/haproxy/haproxy.cfg ]; then
    mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
fi

# Create a new HAProxy configuration file
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000
    timeout client 10000
    timeout server 10000

listen my_custom_listener
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 310219-web-01 54.87.242.202:80 check
    server 310219-web-02 100.26.212.66:80 check
EOF

# Restart HAProxy service to apply the new configuration
service haproxy restart

# Enable HAProxy service to start on system boot
systemctl enable haproxy

